# Generated by Django 4.0.3 on 2022-06-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211206_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['username']},
        ),
    ]
